# for AWS code build
version: 0.2

phases:
  install:
    commands:
      - echo Install started on `date`
      - curl -sS http://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - apt-get update && apt-get install yarn python-pip nodejs --yes
      - apt-get install python-pip
      - pip install awscli --upgrade --user
      - ln -s /usr/bin/nodejs /usr/bin/node
      - echo Install completed on `date` 
  build:
    commands:
      - echo Build started on `date`
      - make ENVIRONMENT_FILE=$EnvFileLocation
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Cleanup started on `date`
      - ~/.local/bin/aws s3 cp $Environments . --recursive
      - ~/.local/bin/aws s3 cp $AppSpec . --recursive
      - ~/.local/bin/aws s3 cp $Scripts . --recursive
      - zip hacksite_build.zip environments/ appspec.yml scripts/ webdist/ Hacksite
      - echo Cleanup finished on `date`
artifacts:
  files:
    - hacksite_build.zip
