version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/darwinfroese/hacksite/
    steps:
      - checkout
      - run: 
          name: Setup build environment
          command: make setup-go
      - run: 
          name: Build Server
          command: make server ENVIRONMENT_FILE=environments/test.env.json
      - run:
          name: Test backend server
          command: go test -v ./...
  build-web:
    docker:
      - image: circleci/node:4.8.2
    working_directory: ~/hacksite
    steps:
      - checkout
      - run:
          name: Update NPM
          command: 'sudo npm install -g npm@latest'
      # - run:
      #     name: Setup global dependencies
      #     command: 'sudo sh scripts/setup-global-deps.sh'
      - run: 
          name: Setup build environment
          command: make setup-web
      - run:
          name: Build web client
          command: make web      
  test-web:
    docker:
      - image: circleci/node:4.8.2-browsers
    working_directory: ~/hacksite
    steps:
      - checkout
      - run:
          name: Update NPM
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Installing Dependencies
          command: 'sudo npm install -g cross-env'
      - run:
          name: Test web client
          command: cd webclient && yarn run test
workflows:
  version: 2
  build_full:
    jobs:
      - build
      - build-web
      - test-web:
          requires:
            - build-web
